name: recommenders
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip>=20.2
  - notebook>=6.4,<7.0
  - ipykernel>=6.0
  - jupyterlab>=3.0,<4.0
  - matplotlib>=3.3,<4.0
  - seaborn>=0.11,<1.0
  - pandas>=1.2,<2.0
  - numpy>=1.19,<2.0
  - scipy>=1.5,<2.0
  - scikit-learn>=0.24,<1.1
  - lightgbm>=3.2,<4.0
  - tensorflow>=2.4,<2.6
  - tensorflow-datasets>=4.0,<5.0
  - transformers>=4.0,<5.0
  - nltk>=3.5,<4.0
  - pyarrow>=2.0,<5.0
  - pyspark>=3.1,<3.3
  - fastai>=2.4,<2.6
  - pip:
    - recommenders
    - cornac>=1.13,<2.0
    - memory-profiler>=0.58,<1.0
    - retrying>=1.3,<2.0
    - pandera[strategies]>=0.6.5,<0.10
    - nni==1.5
    - xlearn==0.40a1
    - vowpalwabbit>=8.8.1,<9.0
    - pymanopt>=0.2.5
    - lightfm>=1.15,<2.0
    - category-encoders>=2.2,<3.0
